name: TUI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python unit tests
      run: |
        python -m unittest discover -s tests/python_unittests/
    - name: Run Pytest TUI tests
      run: |
        python -m pytest tests/pytest_tests/test_tui.py
